export const PLAYER = {
  eyeHeight: 1.65,
  radius: 0.38,
  walkSpeed: 4.65,
  sprintMultiplier: 1.32,
  acceleration: 15,
  deceleration: 18,
  lookSensitivity: 0.00175,
  maxPitchUp: Math.PI / 2.45,
  maxPitchDown: -Math.PI / 2.2,
};

export const SCANNER = {
  range: 9,
  colorHealthy: 0x00ffb0,
  colorRisk: 0xff3355,
  jointColor: 0x00d4ff,
};

export const OFFICE = {
  width: 38,
  depth: 34,
  wallHeight: 3.2,
  transformCold: 0x182232,
  transformWarm: 0xf2f6f8,
};

export const SHOP_ITEMS = [
  {
    id: 'ergonomic_chair',
    name: 'Silla ergonomica',
    desc: 'Soporte lumbar ajustable y reposabrazos regulables',
    icon: '🪑',
    price: 450,
    category: 'furniture',
    effects: { spine: -10, neck: -5, fatigue: -20, prod: 15 },
    tags: ['espalda', 'lumbar', 'postura'],
  },
  {
    id: 'monitor_stand',
    name: 'Soporte monitor',
    desc: 'Eleva la pantalla al nivel de los ojos',
    icon: '🖥️',
    price: 120,
    category: 'accessory',
    effects: { neck: -15, spine: -5, fatigue: -10, prod: 10 },
    tags: ['cuello', 'monitor'],
  },
  {
    id: 'wrist_rest',
    name: 'Reposamunecas',
    desc: 'Almohadilla ergonomica para teclado',
    icon: '⌨️',
    price: 35,
    category: 'accessory',
    effects: { wrist: -12, fatigue: -8, prod: 8 },
    tags: ['munecas', 'manos'],
  },
  {
    id: 'footrest',
    name: 'Reposapies',
    desc: 'Apoya los pies en angulo correcto',
    icon: '🦶',
    price: 65,
    category: 'accessory',
    effects: { spine: -5, fatigue: -12, prod: 5 },
    tags: ['piernas', 'circulacion'],
  },
  {
    id: 'standing_desk',
    name: 'Mesa elevable',
    desc: 'Permite alternar trabajo de pie y sentado',
    icon: '📐',
    price: 350,
    category: 'furniture',
    effects: { spine: -20, neck: -10, fatigue: -25, prod: 20 },
    tags: ['premium', 'postura'],
  },
  {
    id: 'active_break',
    name: 'Pausas activas',
    desc: 'Programa de estiramientos guiados cada 2h',
    icon: '🧘',
    price: 200,
    category: 'training',
    effects: { fatigue: -30, prod: 15 },
    tags: ['fatiga', 'equipo'],
  },
  {
    id: 'office_lighting',
    name: 'Iluminacion LED',
    desc: 'Luz de espectro completo sin parpadeo',
    icon: '💡',
    price: 500,
    category: 'environment',
    effects: { fatigue: -15, prod: 10 },
    tags: ['ojos', 'global'],
  },
  {
    id: 'ergo_training',
    name: 'Formacion ergonomica',
    desc: 'Taller de higiene postural para el equipo',
    icon: '📚',
    price: 300,
    category: 'training',
    effects: { neck: -5, spine: -5, prod: 12 },
    tags: ['conciencia', 'equipo'],
  },
];
